### ISSUE TITLE
[BUG] Throwable weapons never recharge their cooldown.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#90] opened 2024-12-22 04:05 UTC

**Comment by pearuhdox** [comment] 2024-12-22 05:21
This needs more info, they seem to work perfectly fine in all tests.

**Comment by pearuhdox** [comment] 2024-12-22 06:29
Closing the issue as invalid, not a bug - world reload required between commits pushes.

**Closed as completed by pearuhdox** 2024-12-22 06:29 UTC
Labels: invalid, question
