### ISSUE TITLE
[BUG] Passive enchants still apply their effects after the player has unequipped the enchanted item.

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#83] opened 2024-12-20 04:56 UTC
I was testing abberation at it's max level and saw that I still have 50 levels of abberation despite having unequipped everything.

**Comment by Mad-Science-Matt** [comment] 2024-12-20 04:57
Manually setting ca.ench_aberration_lvl to zero didn't help because something automatically set the enchant back to 50.

**Comment by Mad-Science-Matt** [comment] 2024-12-20 04:58
Something is broken and I can't equip myself with new passive enchants and the level of existing passine enchants won't change.

**Comment by Mad-Science-Matt** [comment] 2024-12-20 04:59
Reloading and leaving the world doesn't work either.

**Comment by pearuhdox** [comment] 2024-12-20 05:50
This specific issue is caused by creative trash not counting as an inventory update, so the system does not trigger until you trigger a full reset (dropping or breaking an item) or move another item in your inventory that has the same enchant. Overall, since this only affects Creative mode, and the system's quirks are important for its performance, I am marking this as won't fix.

**Closed as completed by pearuhdox** 2024-12-20 05:50 UTC
Labels: wontfix
