### ISSUE TITLE
Illegal Torch Placement with Lightborn

### ISSUE THREAD

**Issue by Sequex** [pearuhdox/Cartographer-2.0#50] opened 2024-12-14 23:59 UTC
Lightborn allows you to place torches on surfaces not normally allowed for torch placement. It will also attempt to place over non-solid blocks such as banners, redstone components (like buttons), water, and yes, even torches. On rare cases, this has been observed to even duplicate the dropped block, however replicating this consistently is rather difficult.
![2024-12-15_07 42 04](https://github.com/user-attachments/assets/283fad25-262e-4637-8bc5-124d2658c3e3)

**Comment by pearuhdox** [comment] 2024-12-15 01:44
Intended behavior: Lightborn will not be allowed to place anything if the block beneath it is a raycast-able block.

**Comment by pearuhdox** [comment] 2024-12-15 03:24
Issue has been fixed in core - any further noticed inconsistencies like this with Lightborn should be reported as blocks missing in the `partial_block.json` tag.

**Closed as completed by pearuhdox** 2024-12-15 03:24 UTC
Labels: bug
