### ISSUE TITLE
Distinguish between Minecraft Projectile Protection and Cartographer's Projectile Protection

### ISSUE THREAD

**Issue by Mad-Science-Matt** [pearuhdox/Cartographer-2.0#65] opened 2024-12-16 08:07 UTC

**Comment by Mad-Science-Matt** [comment] 2024-12-16 08:21
How do I distinguish the vanilla one from the carto one in the creative menu?

**Comment by pearuhdox** [comment] 2024-12-16 08:21
This is intentional. Vanilla Projectile Protection is solely changed to be compatible to Curse of Instability.

Cartographer Enchant Rework's Projectile Protection is an alternate enchantment so it can be rebalanced as necessary or so additional features can be added to it should it be necessary.

This is consistent with how Rework also adds and modifies the enchanting table. Vanilla Projectile Protection is not available when Rework is loaded and modifies the availability tags in the enchantment table.

Labeled as won't fix because this is not a bug.

**Comment by pearuhdox** [comment] 2024-12-16 08:25
As an addendum to that issue - I will reopen and modify the issue to state "Distinguish between Minecraft Projectile Protection and Cartographer Projectile Protection"

**Comment by pearuhdox** [comment] 2024-12-16 08:34
For now - Cartographer's Projectile Protection will be known as Ranged Protection.

**Closed as completed by pearuhdox** 2024-12-16 08:34 UTC
Labels: enhancement, reopen
